### ISSUE TITLE
Update PotW initiative status - stopped.

### ISSUE THREAD

**Issue by anurudhp** [iiittheorygroup/iiittheorygroup.github.io#15]
https://iiittheorygroup.github.io/Initiatives says PotW is still happening, could that be moved/removed?
I believe the initiative was stopped months ago.

Also update the "getting started" page with the correct info: https://iiittheorygroup.github.io/Getting-Started

**Comment by iambrj** [comment]
@shash42 please update it to say we have problem of the day now.
